CREATE SCHEMA COMPETENCY;

USE COMPETENCY;

CREATE TABLE EMPLOYEE (
EMPLOYEE_ID VARCHAR(128) NOT NULL,
EMPLOYEE_CODE VARCHAR(10),
EMPLOYEE_NAME VARCHAR(50),
CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID)
);

INSERT INTO EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_CODE,EMPLOYEE_NAME) values ('x1qwd','150061','Sugata Mazumdar');

SELECT * FROM EMPLOYEE;

CREATE TABLE SKILL (
SKILL_ID VARCHAR(128) NOT NULL,
SKILL_NAME VARCHAR(50),
CONSTRAINT PK_SKILL PRIMARY KEY (SKILL_ID)
);

INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('y2sddf','Spring Web - MVC');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('qidhg3','Spring Integration');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('lqwe21','Spring AMQP - Rabbit MQ');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('kqwdy','In Memory DB (*Fire)');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('sdj39','Tomcat server');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('321nb','Spring Data - JPA');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('kj324','Spring security');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('lj32b','Spring REST');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('8721vd','Spring Remoting');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('nqwe21','Spring web services');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('v2137v','Spring Batch');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('28gd21','Spring JMS');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('nmed91','Spring Core');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('opohj6','Messaging');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('08gs72','CloudFoundry');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('76ussw','Architecture & Design');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('iuyv55','Testing');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('uyrtt6','Performance Testing');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) values ('54bsl','Build & deployment Tools');

SELECT * FROM SKILL;

CREATE TABLE EMPLOYEE_SKILL (
EMPLOYEE_SKILL_ID VARCHAR(128) NOT NULL,
EMPLOYEE_ID VARCHAR(128) NOT NULL,
SKILL_ID VARCHAR(128) NOT NULL,
EMPLOYEE_SKILL_RATING INTEGER(5),
CONSTRAINT PK_EMPLOYEE_SKILL PRIMARY KEY (EMPLOYEE_SKILL_ID),
CONSTRAINT FK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
CONSTRAINT FK_SKILL FOREIGN KEY (SKILL_ID) REFERENCES SKILL (SKILL_ID)
);

INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_SKILL_ID, EMPLOYEE_ID, SKILL_ID, EMPLOYEE_SKILL_RATING) VALUES ('kwq6vq','x1qwd','y2sddf',2);

SELECT * FROM EMPLOYEE_SKILL;

